version: '3'
services:
  lumbashark:
    container_name: 'lumbashark_app'
    image: smartsheep-docker.pkg.coding.net/lumba/lumbashark/lumbashark:0.1.1
    ports:
      - '3100:3100'
    links:
      - 'mysql:database'
    depends_on:
      - mysql
    environment:
      DATABASE_URL: 'mysql://root:password@172.22.0.2:3306/lumbashark?schema=public'
  mysql:
    container_name: 'lumbashark_mysql'
    restart: always
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'lumbashark'
      MYSQL_ROOT_PASSWORD: 'password'
