version: "3"
services:
  codingland:
    image: codingland:2.0.1
    # image: xsheep2010/codingland:2.0.1
    ports:
      - "3100:3100"
    depends_on:
      - mysql
      - piston
    env_file:
      - .env
  mysql:
    restart: always
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "codingland"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - db:/var/lib/mysql
  piston:
    image: ghcr.io/engineer-man/piston
    container_name: code_runner
    restart: always
    volumes:
      - piston:/piston
volumes:
  db: {}
  piston: {}
